openapi: "3.0.4"
info:
  title: Stock Trading Sim
  description: "API for my fullstack stock trading simulator"
  version: "1.0"
servers:
  - url: https://api.server.test/api/v1
    description: "Serving Data"

paths:
  /users:
    get:
      tags:
        - User
      responses:
        "200":
          description: "A list of users"
  /users/new:
    post:
      tags:
        - User
      description: ""
      responses:
        "200":
          description: "Returns the new user's id"

components:
  schemas:
    user:
      type: object
      properties:
        id:
          type: integer
